### ISSUE TITLE
All my BBT keys appear as "pinned" in Zotero report

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-report-customizer#13]
With Zotero Report Customizer (ZRC), generating a report for My Library indicates that all my items have "pinned" keys. I don't understand, because I've only edited a few keys (through the extra field) and thought that BBT was, by default, only generating soft keys. I must misunderstanding something.

Isn't a pinned key a *user-generated* (by manually edit of the Extra field or through context menu  -> "Generate BibTeX key") and *fixed/stable* key?
How do soft keys appear appear in Zotero report (with ZRC enabled) ?

ZRC 0.2.16 ; BBT 1.1.1
*BBT Prefs:*
Auto-pin citation keys: No
On conflict, non-pinned key should be : kept

**Comment by retorquere** [comment]
Nope, your understanding is correct -- the default is to generate soft keys, and pinned is exactly what you describe. In BBT, if you click on a reference, the citekey will be in the ref details, if it's in italics, it's a soft key.

In the report, soft keys should be reported as `generated`.

It is possible (but to be honest, not entirely plausible) that this problem is collateral damage from #12. I'd appreciate it if you could test that and see if the problem's gone. If not, could you run a report, and then send a zotplus error report through the gear menu?

**Comment by gracile-fr** [comment]
Still unresolved: what actions should I do before sending a zotplus error report? Generating a Zotero Report with some items?

**Comment by retorquere** [comment]
Yep.

**Comment by gracile-fr** [comment]
ID: GVRUF5TU

**Comment by retorquere** [comment]
Could you try the versino at http://tempsend.com/44CA738885, and then:

* Go into the BBT preferences, Debug tab, en enable enhanced debugging
* Run a report
* Submit  a new debug ID

I had forgotten default debugging only shows errors, not debug logging.

**Comment by gracile-fr** [comment]
ID: 4W93ZATG

**Comment by retorquere** [comment]
Super, thanks; http://tempsend.com/1FC69D31FC should fix it.

**Comment by retorquere** [comment]
I've cut a release, no need to test the tempsend version

**Comment by gracile-fr** [comment]
Thank you!

**Comment by retorquere** [comment]
My pleasure, and thanks for the issue report.
